export default function Privacy() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-16">
      <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50">Privacy Policy</h1>
      <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300">
        <strong>Placeholder content.</strong> This page exists so the signup checkbox links somewhere real — it is not
        a real privacy policy and should be replaced with reviewed legal content before this app is used in
        production.
      </div>
      <div className="mt-6 space-y-4 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
        <p>
          AURA PRO collects the information you provide directly (name, email, order and shipping details) and
          information generated by using the platform (orders, reviews, seller activity), in order to operate the
          marketplace, process orders, and provide customer support.
        </p>
        <p>
          Passwords are never stored in plain text. If you sign in with Google, AURA PRO only receives your verified
          name and email address from Google — never your Google password.
        </p>
        <p>
          AURA PRO does not sell your personal information. Data is shared with third-party services only as
          necessary to operate the platform (e.g. payment processing, transactional email, image hosting).
        </p>
      </div>
    </div>
  );
}
